export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const ADD_LOCATION = 'ADD_LOCATION';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CATEGORY_TEXT_CHANGED = 'CATEGORY_TEXT_CHANGED';
export const LOCATION_TEXT_CHANGED = 'CATEGORY_TEXT_CHANGED';
export const ADDRESS_TEXT_CHANGED = 'ADDRESS_TEXT_CHANGED';
export const CATEGORY_SLIDER_CHANGED = 'CATEGORY_SLIDER_CHANGED';
