export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const ADD_LOCATION = 'ADD_LOCATION';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CATEGORY_TEXT_CHANGED = 'CATEGORY_TEXT_CHANGED';